DROP TABLE PHONE;
DROP TABLE ID_GEN;

CREATE TABLE PHONE (ID INTEGER NOT NULL, NUMBER VARCHAR(255), TYPE VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE ID_GEN (SEQ_NAME VARCHAR(80), SEQ_COUNT INTEGER, PRIMARY KEY (SEQ_NAME));

INSERT INTO ID_GEN (SEQ_NAME, SEQ_COUNT) VALUES ('PhoneId', 0);
