DROP TABLE EMPLOYEE_PROJECT;
DROP TABLE PROJECT;
DROP TABLE EMPLOYEE;


CREATE TABLE PROJECT (ID INTEGER NOT NULL, NAME VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE EMPLOYEE (ID INTEGER NOT NULL, NAME VARCHAR(255), STARTDATE DATE, SALARY BIGINT, PRIMARY KEY (ID));
CREATE TABLE EMPLOYEE_PROJECT (PROJECTS_ID INTEGER NOT NULL, EMPLOYEES_ID INTEGER NOT NULL,
                               CONSTRAINT PROJECTS_FK FOREIGN KEY (PROJECTS_ID) REFERENCES PROJECT (ID),
                               CONSTRAINT EMPLOYEES_FK FOREIGN KEY (EMPLOYEES_ID) REFERENCES EMPLOYEE (ID),
                               PRIMARY KEY (PROJECTS_ID, EMPLOYEES_ID));


INSERT INTO EMPLOYEE (ID, NAME, SALARY, STARTDATE) VALUES (1, 'Joan', 59000, {d '2003-04-16'});
INSERT INTO EMPLOYEE (ID, NAME, SALARY, STARTDATE) VALUES (2, 'Sarah', 52000, {d '2002-04-26'});
INSERT INTO EMPLOYEE (ID, NAME, SALARY, STARTDATE) VALUES (3, 'John', 55000, {d '2001-01-01'});
INSERT INTO EMPLOYEE (ID, NAME, SALARY, STARTDATE) VALUES (4, 'Roberts', 53000, {d '2001-05-23'});
INSERT INTO EMPLOYEE (ID, NAME, SALARY, STARTDATE) VALUES (5, 'Peter', 50000, {d '2002-08-06'});
INSERT INTO EMPLOYEE (ID, NAME, SALARY, STARTDATE) VALUES (6, 'Frank', 51000, {d '2003-02-17'});
INSERT INTO EMPLOYEE (ID, NAME, SALARY, STARTDATE) VALUES (7, 'Scott', 60000, {d '2004-11-14'});
INSERT INTO EMPLOYEE (ID, NAME, SALARY, STARTDATE) VALUES (8, 'Sue', 62000, {d '2005-08-18'});
INSERT INTO EMPLOYEE (ID, NAME, SALARY, STARTDATE) VALUES (9, 'Stephanie', 54000, {d '2006-06-07'});
INSERT INTO EMPLOYEE (ID, NAME, SALARY, STARTDATE) VALUES (10, 'Jennifer', 55000, {d '1999-08-11'});
INSERT INTO EMPLOYEE (ID, NAME, SALARY, STARTDATE) VALUES (11, 'Marcus', 35000, {d '1995-07-22'});

INSERT INTO PROJECT (ID, NAME) VALUES (1, 'Design Release2');
INSERT INTO PROJECT (ID, NAME) VALUES (2, 'Implement Release2');
INSERT INTO PROJECT (ID, NAME) VALUES (3, 'Test Release2');
INSERT INTO PROJECT (ID, NAME) VALUES (4, 'Release3');