DROP TABLE EMPLOYEE;

CREATE TABLE EMPLOYEE (ID INTEGER NOT NULL, NAME VARCHAR(255), VACN_HOURS INTEGER, PRIMARY KEY (ID));

INSERT INTO EMPLOYEE (ID, NAME, VACN_HOURS) VALUES (1, 'John', 48);
INSERT INTO EMPLOYEE (ID, NAME, VACN_HOURS) VALUES (2, 'Paul', 64);
INSERT INTO EMPLOYEE (ID, NAME, VACN_HOURS) VALUES (3, 'Sarah', 22);
INSERT INTO EMPLOYEE (ID, NAME, VACN_HOURS) VALUES (4, 'Patrick', 36);
INSERT INTO EMPLOYEE (ID, NAME, VACN_HOURS) VALUES (5, 'Joan', 40);
INSERT INTO EMPLOYEE (ID, NAME, VACN_HOURS) VALUES (6, 'Samantha', 18);
INSERT INTO EMPLOYEE (ID, NAME, VACN_HOURS) VALUES (7, 'Mark', 78);
INSERT INTO EMPLOYEE (ID, NAME, VACN_HOURS) VALUES (8, 'Ryan', 28);
INSERT INTO EMPLOYEE (ID, NAME, VACN_HOURS) VALUES (9, 'Jackie', 82);

