DROP TABLE EMP_PROJ;
DROP TABLE EMPLOYEE;
DROP TABLE PROJECT;

CREATE TABLE PROJECT (ID INTEGER  NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
                      NAME VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE EMPLOYEE (ID INTEGER  NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
                       NAME VARCHAR(255), SALARY BIGINT, PRIMARY KEY (ID));
CREATE TABLE EMP_PROJ (PROJ_ID INTEGER NOT NULL, EMP_ID INTEGER NOT NULL,
                       CONSTRAINT PROJ_FK FOREIGN KEY (PROJ_ID) REFERENCES PROJECT (ID),
                       CONSTRAINT EMP_FK FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (ID), 
                       PRIMARY KEY (PROJ_ID, EMP_ID))

