DROP TABLE LOGRECORD;

CREATE TABLE LOGRECORD (ID INTEGER  NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
                        EMPNO INTEGER, ACTION VARCHAR(255), PRIMARY KEY (ID));