DROP TABLE EMPLOYEE;
DROP TABLE EMPLOYEEHISTORY;
CREATE TABLE EMPLOYEEHISTORY (EMP_ID INTEGER NOT NULL, PRIMARY KEY (EMP_ID));
CREATE TABLE EMPLOYEE (ID INTEGER, NAME VARCHAR(255), SALARY BIGINT, PRIMARY KEY (ID))