DROP TABLE PROJECT;
DROP TABLE DEPARTMENT;

CREATE TABLE DEPARTMENT (NUM INTEGER NOT NULL, COUNTRY VARCHAR(255), NAME VARCHAR(255), PRIMARY KEY (NUM, COUNTRY));
CREATE TABLE PROJECT (NAME VARCHAR(255) NOT NULL, DEPT_NUM INTEGER NOT NULL, DEPT_CTRY VARCHAR(255), START_DATE DATE, END_DATE DATE, PRIMARY KEY (NAME, DEPT_NUM, DEPT_CTRY));

INSERT INTO DEPARTMENT(NUM, COUNTRY, NAME) VALUES (1, 'CA', 'Engineering');
INSERT INTO PROJECT (NAME, DEPT_NUM, DEPT_CTRY, START_DATE, END_DATE) VALUES ('Release3', 1, 'CA', {d '2002-12-05'}, {d '2002-08-06'});
