DROP TABLE ORDERITEM;
DROP TABLE CUSTOMERORDER;

CREATE TABLE CUSTOMERORDER (ID INTEGER NOT NULL, PRIMARY KEY (ID));
CREATE TABLE ORDERITEM (ID INTEGER NOT NULL, NAME VARCHAR(255), QUANTITY INTEGER, ITEMS_KEY VARCHAR(255), ORDER_ID INTEGER, PRIMARY KEY (ID));
