DROP TABLE PROJECT;
DROP TABLE DEPARTMENT;
CREATE TABLE DEPARTMENT (NAME VARCHAR(255), NUM INTEGER NOT NULL, CTRY VARCHAR(255) NOT NULL, PRIMARY KEY (NUM, CTRY));
-- DDL generated - do not use
--CREATE TABLE DEPARTMENT (DEPT BLOB(2147483647) NOT NULL, NAME VARCHAR(255), PRIMARY KEY (DEPT));
--CREATE TABLE DEPARTMENT(ID INTEGER NOT NULL, NAME VARCHAR(255), PRIMARY KEY(ID));

CREATE TABLE PROJECT (START_DATE DATE, END_DATE DATE, P_NAME VARCHAR(255) NOT NULL, DEPT_NUM INTEGER NOT NULL, DEPT_CTRY VARCHAR(255) NOT NULL, PRIMARY KEY (P_NAME, DEPT_NUM, DEPT_CTRY));
-- DDL generated - do not use
--CREATE TABLE PROJECT (NAME VARCHAR(255) NOT NULL, START_DATE DATE, END_DATE DATE, DEPT_DEPT BLOB(2147483647) NOT NULL, PRIMARY KEY (NAME, DEPT_DEPT));
--CREATE TABLE PROJECT (DEPT_ID INTEGER NOT NULL, NAME VARCHAR(255) NOT NULL, 
--                      START_DATE DATE, END_DATE DATE, PRIMARY KEY(DEPT_ID,NAME),
--                      CONSTRAINT DEPT_FK FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(ID));

INSERT INTO DEPARTMENT(NUM, CTRY, NAME) VALUES (1, 'CA', 'Engineering');
INSERT INTO PROJECT (DEPT_NUM, DEPT_CTRY, P_NAME, START_DATE, END_DATE) VALUES (1, 'CA', 'Release3', {d '2002-12-05'}, {d '2002-08-06'});
