DROP TABLE EMPLOYEE;

CREATE TABLE EMPLOYEE (ID INTEGER NOT NULL, NAME VARCHAR(255), LASTACCESSTIME TIMESTAMP, PRIMARY KEY (ID));

INSERT INTO EMPLOYEE (ID, NAME) VALUES (1, 'Joan');
INSERT INTO EMPLOYEE (ID, NAME) VALUES (2, 'Sarah');
INSERT INTO EMPLOYEE (ID, NAME) VALUES (3, 'John');
INSERT INTO EMPLOYEE (ID, NAME) VALUES (4, 'Roberts');
INSERT INTO EMPLOYEE (ID, NAME) VALUES (5, 'Peter');