DROP TABLE EMPLOYEE;
DROP TABLE SEQUENCE;

CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(64), SEQ_COUNT INTEGER);
CREATE TABLE EMPLOYEE (ID INTEGER NOT NULL, NAME VARCHAR(255), SALARY BIGINT, PRIMARY KEY (ID));

INSERT INTO SEQUENCE (SEQ_NAME, SEQ_COUNT ) VALUES('SEQ_GEN',1);
