DROP TABLE EMP;
DROP TABLE EMP_ADDRESS;

CREATE TABLE EMP (ID INTEGER NOT NULL, NAME VARCHAR(255), SALARY BIGINT, PRIMARY KEY (ID));
CREATE TABLE EMP_ADDRESS (EMP_ID INTEGER NOT NULL, STREET VARCHAR(255), 
                  CITY VARCHAR(255), STATE VARCHAR(255), ZIP_CODE VARCHAR(255), PRIMARY KEY (EMP_ID));
