DROP TABLE EMP_PROJECT;
DROP TABLE EMPLOYEE;
DROP TABLE PROJECT;

CREATE TABLE PROJECT (ID INTEGER  NOT NULL, NAME VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE EMPLOYEE (COUNTRY VARCHAR(255) NOT NULL, EMP_ID INTEGER NOT NULL, NAME VARCHAR(255),
                       SALARY BIGINT, MGR_COUNTRY VARCHAR(255), MGR_ID INTEGER, PRIMARY KEY(COUNTRY,EMP_ID),
                       CONSTRAINT MGR_FK FOREIGN KEY (MGR_COUNTRY,MGR_ID) REFERENCES EMPLOYEE (COUNTRY,EMP_ID));
CREATE TABLE EMP_PROJECT (PROJECT_ID INTEGER NOT NULL, EMP_COUNTRY VARCHAR(255) NOT NULL, EMP_ID INTEGER NOT NULL,
                          CONSTRAINT PROJECT_FK FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (ID),
                          CONSTRAINT EMPLOYEE_FK FOREIGN KEY (EMP_COUNTRY,EMP_ID) REFERENCES EMPLOYEE (COUNTRY,EMP_ID),
                          PRIMARY KEY (PROJECT_ID,EMP_COUNTRY,EMP_ID));


INSERT INTO PROJECT (ID, NAME) VALUES (4, 'Release3');
INSERT INTO EMPLOYEE (COUNTRY, EMP_ID, NAME, SALARY, MGR_COUNTRY, MGR_ID) VALUES ('Canada', 1, 'John', 55000, NULL, NULL);
INSERT INTO EMPLOYEE (COUNTRY, EMP_ID, NAME, SALARY, MGR_COUNTRY, MGR_ID) VALUES ('Canada', 2, 'Paul', 55000, 'Canada', 1);
INSERT INTO EMP_PROJECT (PROJECT_ID, EMP_COUNTRY, EMP_ID) VALUES (4, 'Canada', 1);
