DROP TABLE UNIFORM;
DROP TABLE EMPLOYEE;

CREATE TABLE EMPLOYEE(ID INTEGER  NOT NULL, NAME VARCHAR(255), COST FLOAT, VERSION INTEGER, PRIMARY KEY (ID));
CREATE TABLE UNIFORM (ID INTEGER  NOT NULL, COLOR VARCHAR(255), EMPLOYEE_ID INTEGER, PRIMARY KEY (ID),
                      CONSTRAINT EMP_FK FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (ID));


INSERT INTO EMPLOYEE (ID, NAME, COST, VERSION) VALUES (2, 'Joan', 0, 0);
INSERT INTO EMPLOYEE (ID, NAME, COST, VERSION) VALUES (1, 'Sarah', 0, 0);

INSERT INTO UNIFORM (ID, COLOR, EMPLOYEE_ID) VALUES (1, 'Blue', 1);
INSERT INTO UNIFORM (ID, COLOR) VALUES (2, 'White');
INSERT INTO UNIFORM (ID, COLOR) VALUES (3, 'Black');
INSERT INTO UNIFORM (ID, COLOR) VALUES (4, 'Red');

