DROP TABLE EMPLOYEE;
DROP TABLE DEPARTMENT;
CREATE TABLE DEPARTMENT (ID INTEGER  NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
                         NAME VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE EMPLOYEE (ID INTEGER  NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
                       NAME VARCHAR(255), SALARY BIGINT, DEPT_ID INT, PRIMARY KEY (ID),
                       CONSTRAINT DEPT_FK FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(ID));

INSERT INTO DEPARTMENT (NAME) VALUES ('Engineering');
INSERT INTO DEPARTMENT (NAME) VALUES ('Human Resources');
INSERT INTO EMPLOYEE (NAME, SALARY, DEPT_ID) VALUES ('Jane Smith', 43000, 1);
INSERT INTO EMPLOYEE (NAME, SALARY, DEPT_ID) VALUES ('John Plaid', 40000, 2);
INSERT INTO EMPLOYEE (NAME, SALARY, DEPT_ID) VALUES ('Bob Danish', 51000, 1);
