DROP TABLE EMPLOYEE;

CREATE TABLE EMPLOYEE (ID INTEGER NOT NULL, NAME VARCHAR(255), SALARY BIGINT, PRIMARY KEY (ID));

INSERT INTO EMPLOYEE (ID, NAME, SALARY) VALUES (1, 'Joan', 59000);
INSERT INTO EMPLOYEE (ID, NAME, SALARY) VALUES (2, 'Sarah', 52000);
INSERT INTO EMPLOYEE (ID, NAME, SALARY) VALUES (3, 'John', 55000);
INSERT INTO EMPLOYEE (ID, NAME, SALARY) VALUES (4, 'Roberts', 53000);
INSERT INTO EMPLOYEE (ID, NAME, SALARY) VALUES (5, 'Peter', 50000);
INSERT INTO EMPLOYEE (ID, NAME, SALARY) VALUES (6, 'Frank', 51000);
INSERT INTO EMPLOYEE (ID, NAME, SALARY) VALUES (7, 'Scott', 60000);
INSERT INTO EMPLOYEE (ID, NAME, SALARY) VALUES (8, 'Sue', 62000);
INSERT INTO EMPLOYEE (ID, NAME, SALARY) VALUES (9, 'Stephanie', 54000);
INSERT INTO EMPLOYEE (ID, NAME, SALARY) VALUES (10, 'Jennifer', 55000);
INSERT INTO EMPLOYEE (ID, NAME, SALARY) VALUES (11, 'Marcus', 35000);