DROP TABLE EMPLOYEE;
DROP TABLE PARKING_SPACE;

CREATE TABLE PARKING_SPACE (ID INTEGER NOT NULL, LOT INTEGER, LOCATION VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE EMPLOYEE (ID INTEGER NOT NULL, NAME VARCHAR(255), PSPACE_ID INTEGER, PRIMARY KEY (ID),
                       CONSTRAINT PSPACE_FK FOREIGN KEY (PSPACE_ID) REFERENCES PARKING_SPACE(ID));

INSERT INTO PARKING_SPACE (ID, LOT, LOCATION) VALUES (1, 1, 'East Lot');
INSERT INTO PARKING_SPACE (ID, LOT, LOCATION) VALUES (2, 2, 'West Lot');
INSERT INTO PARKING_SPACE (ID, LOT, LOCATION) VALUES (3, 3, 'North Lot');
INSERT INTO PARKING_SPACE (ID, LOT, LOCATION) VALUES (4, 4, 'South Lot');
INSERT INTO PARKING_SPACE (ID, LOT, LOCATION) VALUES (5, 5, 'West Lot');

INSERT INTO EMPLOYEE (ID, NAME, PSPACE_ID) VALUES (1, 'Joan', 1);
INSERT INTO EMPLOYEE (ID, NAME, PSPACE_ID) VALUES (2, 'Sarah', 2);
INSERT INTO EMPLOYEE (ID, NAME, PSPACE_ID) VALUES (3, 'John', 3);
INSERT INTO EMPLOYEE (ID, NAME, PSPACE_ID) VALUES (4, 'Roberts', 4);
INSERT INTO EMPLOYEE (ID, NAME, PSPACE_ID) VALUES (5, 'Peter', 5);
