DROP TABLE ORG_STRUCTURE;
DROP TABLE EMP_LOB;
DROP TABLE EMPLOYEE;

CREATE TABLE EMPLOYEE (COUNTRY VARCHAR(255) NOT NULL, EMP_ID INTEGER NOT NULL, NAME VARCHAR(255), 
                       SALARY BIGINT, PRIMARY KEY(COUNTRY,EMP_ID));
CREATE TABLE EMP_LOB (COUNTRY VARCHAR(255) NOT NULL, ID INTEGER NOT NULL, PHOTO BLOB, COMMENTS CLOB, 
                      PRIMARY KEY(COUNTRY,ID),
                      CONSTRAINT EMPLOYEE_FK FOREIGN KEY (COUNTRY,ID) REFERENCES EMPLOYEE (COUNTRY,EMP_ID));
CREATE TABLE ORG_STRUCTURE (COUNTRY VARCHAR(255) NOT NULL, EMP_ID INTEGER NOT NULL, 
                            MGR_COUNTRY VARCHAR(255), MGR_ID INTEGER, PRIMARY KEY(COUNTRY,EMP_ID),
                            CONSTRAINT MGR_FK FOREIGN KEY (MGR_COUNTRY,MGR_ID) REFERENCES EMPLOYEE (COUNTRY,EMP_ID),
                            CONSTRAINT EMPLOYEE_FK2 FOREIGN KEY (COUNTRY,EMP_ID) REFERENCES EMPLOYEE (COUNTRY,EMP_ID));

INSERT INTO EMPLOYEE (COUNTRY, EMP_ID, NAME, SALARY) VALUES ('Canada', 1, 'John', 55000);
INSERT INTO EMPLOYEE (COUNTRY, EMP_ID, NAME, SALARY) VALUES ('Canada', 2, 'Paul', 55000);
INSERT INTO EMP_LOB (COUNTRY, ID, PHOTO, COMMENTS) VALUES ('Canada', 1, NULL, NULL);
INSERT INTO EMP_LOB (COUNTRY, ID, PHOTO, COMMENTS) VALUES ('Canada', 2, NULL, NULL);
INSERT INTO ORG_STRUCTURE (COUNTRY, EMP_ID, MGR_COUNTRY, MGR_ID) VALUES ('Canada', 1, NULL, NULL);
INSERT INTO ORG_STRUCTURE (COUNTRY, EMP_ID, MGR_COUNTRY, MGR_ID) VALUES ('Canada', 2, 'Canada', 1);
