DROP TABLE EMPLOYEE_STAGE;

CREATE TABLE EMPLOYEE_STAGE (ID INTEGER NOT NULL, NAME VARCHAR(255), START_DATE DATE, DAILY_RATE INTEGER, TERM INTEGER,
                             VACATION INTEGER, HOURLY_RATE FLOAT, SALARY BIGINT, PENSION BIGINT, TYPE VARCHAR(32), 
                             PRIMARY KEY (ID));

INSERT INTO EMPLOYEE_STAGE (ID, NAME, START_DATE, DAILY_RATE, TERM, VACATION, HOURLY_RATE, SALARY, PENSION, TYPE) 
                            VALUES (1, 'John', {d '2001-01-01'}, 500, 12, NULL, NULL, NULL, NULL, 'ContractEmployee');
INSERT INTO EMPLOYEE_STAGE (ID, NAME, START_DATE, DAILY_RATE, TERM, VACATION, HOURLY_RATE, SALARY, PENSION, TYPE) 
                            VALUES (2, 'Paul', {d '2002-04-08'}, 600, 24, NULL, NULL, NULL, NULL, 'ContractEmployee');
INSERT INTO EMPLOYEE_STAGE (ID, NAME, START_DATE, DAILY_RATE, TERM, VACATION, HOURLY_RATE, SALARY, PENSION, TYPE) 
                            VALUES (3, 'Sarah', {d '2003-06-10'}, 700, 18, NULL, NULL, NULL, NULL, 'ContractEmployee');

INSERT INTO EMPLOYEE_STAGE (ID, NAME, START_DATE, DAILY_RATE, TERM, VACATION, HOURLY_RATE, SALARY, PENSION, TYPE) 
                            VALUES (4, 'Patrick', {d '2004-07-01'}, NULL, NULL, 15, NULL, 55000, 100000, 'FTEmp');
INSERT INTO EMPLOYEE_STAGE (ID, NAME, START_DATE, DAILY_RATE, TERM, VACATION, HOURLY_RATE, SALARY, PENSION, TYPE) 
                            VALUES (5, 'Joan', {d '2003-09-09'}, NULL, NULL, 15, NULL, 59000, 200000, 'FTEmp');
INSERT INTO EMPLOYEE_STAGE (ID, NAME, START_DATE, DAILY_RATE, TERM, VACATION, HOURLY_RATE, SALARY, PENSION, TYPE) 
                            VALUES (6, 'Samantha', {d '2000-03-12'}, NULL, NULL, 20, NULL, 60000, 450000, 'FTEmp');

INSERT INTO EMPLOYEE_STAGE (ID, NAME, START_DATE, DAILY_RATE, TERM, VACATION, HOURLY_RATE, SALARY, PENSION, TYPE) 
                            VALUES (7, 'Mark', {d '2004-11-01'}, NULL, NULL, 15, 17.0, NULL, NULL, 'PTEmp');
INSERT INTO EMPLOYEE_STAGE (ID, NAME, START_DATE, DAILY_RATE, TERM, VACATION, HOURLY_RATE, SALARY, PENSION, TYPE) 
                            VALUES (8, 'Ryan', {d '2005-12-05'}, NULL, NULL, 15, 16.0, NULL, NULL, 'PTEmp');
INSERT INTO EMPLOYEE_STAGE (ID, NAME, START_DATE, DAILY_RATE, TERM, VACATION, HOURLY_RATE, SALARY, PENSION, TYPE) 
                            VALUES (9, 'Jackie', {d '2006-01-03'}, NULL, NULL, 10, 15.0, NULL, NULL, 'PTEmp');

