DROP TABLE USER_DB;

CREATE TABLE USER_DB (NAME VARCHAR(255) NOT NULL, PASSWORD VARCHAR(255), LASTCHANGE DATE, PRIMARY KEY (NAME));

INSERT INTO USER_DB (NAME, PASSWORD, LASTCHANGE) VALUES ('Joan', 'foo', {d '2003-04-16'});
INSERT INTO USER_DB (NAME, PASSWORD, LASTCHANGE) VALUES ('Sarah', 'bar', {d '2002-04-26'});
INSERT INTO USER_DB (NAME, PASSWORD, LASTCHANGE) VALUES ('John', 'password', {d '2001-01-01'});
INSERT INTO USER_DB (NAME, PASSWORD, LASTCHANGE) VALUES ('Roberts', 'hello', {d '2001-05-23'});
INSERT INTO USER_DB (NAME, PASSWORD, LASTCHANGE) VALUES ('Peter', '1234', {d '2002-08-06'});
INSERT INTO USER_DB (NAME, PASSWORD, LASTCHANGE) VALUES ('Frank', 'myPassword', {d '2003-02-17'});
INSERT INTO USER_DB (NAME, PASSWORD, LASTCHANGE) VALUES ('Scott', 'persistence', {d '2004-11-14'});
INSERT INTO USER_DB (NAME, PASSWORD, LASTCHANGE) VALUES ('Sue', '5678', {d '2005-08-18'});
INSERT INTO USER_DB (NAME, PASSWORD, LASTCHANGE) VALUES ('Stephanie', 'ejb', {d '2006-06-07'});
INSERT INTO USER_DB (NAME, PASSWORD, LASTCHANGE) VALUES ('Jennifer', 'pwd', {d '1999-08-11'});
INSERT INTO USER_DB (NAME, PASSWORD, LASTCHANGE) VALUES ('Marcus', 'foobar', {d '2013-12-22'});