DROP TABLE EMPLOYEE;

CREATE TABLE EMPLOYEE (ID INTEGER NOT NULL, NAME VARCHAR(255), STARTDATE DATE, SALARY BIGINT, PRIMARY KEY (ID));

INSERT INTO EMPLOYEE (ID, NAME, SALARY) VALUES (1, 'Joan', 59000);
INSERT INTO EMPLOYEE (ID, NAME, SALARY) VALUES (2, 'Sarah', 52000);
INSERT INTO EMPLOYEE (ID, NAME, SALARY) VALUES (3, 'John', 55000);