DROP TABLE EMP_PROJECT;
DROP TABLE EMPLOYEE;
DROP TABLE PROJECT;

CREATE TABLE PROJECT (ID INTEGER  NOT NULL, NAME VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE EMPLOYEE (ID INTEGER NOT NULL, NAME VARCHAR(255), SALARY BIGINT, PRIMARY KEY(ID));
CREATE TABLE EMP_PROJECT (PROJECT_ID INTEGER NOT NULL, EMP_ID INTEGER NOT NULL, START_DATE DATE,
                          CONSTRAINT PROJECT_FK FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (ID),
                          CONSTRAINT EMPLOYEE_FK FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (ID),
                          PRIMARY KEY (PROJECT_ID,EMP_ID));


INSERT INTO PROJECT (ID, NAME) VALUES (3, 'Release2');
INSERT INTO PROJECT (ID, NAME) VALUES (4, 'Release3');
INSERT INTO EMPLOYEE (ID, NAME, SALARY) VALUES (1, 'John', 55000);
INSERT INTO EMP_PROJECT (PROJECT_ID, EMP_ID, START_DATE) VALUES (4, 1, {d '2002-08-06'});
