DROP TABLE CONTRACT_EMP;
DROP TABLE PT_EMP;
DROP TABLE FT_EMP;
DROP TABLE EMP;

CREATE TABLE EMP (ID INTEGER NOT NULL, NAME VARCHAR(255), S_DATE DATE, EMP_TYPE INTEGER, PRIMARY KEY (ID));
CREATE TABLE FT_EMP (ID INTEGER NOT NULL, VACATION INTEGER, SALARY BIGINT, PENSION BIGINT, PRIMARY KEY (ID),
                     CONSTRAINT FT_EMP_FK FOREIGN KEY (ID) REFERENCES EMP(ID));
CREATE TABLE PT_EMP (ID INTEGER NOT NULL, VACATION INTEGER, H_RATE FLOAT, PRIMARY KEY (ID),
                     CONSTRAINT PT_EMP_FK FOREIGN KEY (ID) REFERENCES EMP(ID));
CREATE TABLE CONTRACT_EMP (ID INTEGER NOT NULL, D_RATE INTEGER, TERM INTEGER, PRIMARY KEY (ID),
                           CONSTRAINT CONTRACT_EMP_FK FOREIGN KEY (ID) REFERENCES EMP(ID));


INSERT INTO EMP (ID, NAME, S_DATE, EMP_TYPE) VALUES (1, 'John', {d '2001-01-01'}, 1);
INSERT INTO EMP (ID, NAME, S_DATE, EMP_TYPE) VALUES (2, 'Paul', {d '2002-04-08'}, 1);
INSERT INTO EMP (ID, NAME, S_DATE, EMP_TYPE) VALUES (3, 'Sarah', {d '2003-06-10'}, 1);
INSERT INTO EMP (ID, NAME, S_DATE, EMP_TYPE) VALUES (4, 'Patrick', {d '2004-07-01'}, 2);
INSERT INTO EMP (ID, NAME, S_DATE, EMP_TYPE) VALUES (5, 'Joan', {d '2003-09-09'}, 2);
INSERT INTO EMP (ID, NAME, S_DATE, EMP_TYPE) VALUES (6, 'Samantha', {d '2000-03-12'}, 2);
INSERT INTO EMP (ID, NAME, S_DATE, EMP_TYPE) VALUES (7, 'Mark', {d '2004-11-01'}, 3);
INSERT INTO EMP (ID, NAME, S_DATE, EMP_TYPE) VALUES (8, 'Ryan', {d '2005-12-05'}, 3);
INSERT INTO EMP (ID, NAME, S_DATE, EMP_TYPE) VALUES (9, 'Jackie', {d '2006-01-03'}, 3);

INSERT INTO CONTRACT_EMP (ID, D_RATE, TERM) VALUES (1, 500, 12);
INSERT INTO CONTRACT_EMP (ID, D_RATE, TERM) VALUES (2, 600, 24);
INSERT INTO CONTRACT_EMP (ID, D_RATE, TERM) VALUES (3, 700, 18);

INSERT INTO FT_EMP (ID, VACATION, SALARY, PENSION) VALUES (4, 15, 55000, 100000);
INSERT INTO FT_EMP (ID, VACATION, SALARY, PENSION) VALUES (5, 15, 59000, 200000);
INSERT INTO FT_EMP (ID, VACATION, SALARY, PENSION) VALUES (6, 20, 60000, 450000);

INSERT INTO PT_EMP (ID, VACATION, H_RATE) VALUES (7, 15, 17.0);
INSERT INTO PT_EMP (ID, VACATION, H_RATE) VALUES (8, 15, 16.0);
INSERT INTO PT_EMP (ID, VACATION, H_RATE) VALUES (9, 10, 15.0);

