DROP TABLE EMPLOYEE;
DROP TABLE PARKING_SPACE;

CREATE TABLE PARKING_SPACE (ID INTEGER  NOT NULL, LOT INTEGER, LOCATION VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE EMPLOYEE (ID INTEGER  NOT NULL, NAME VARCHAR(255), SALARY BIGINT, PRIMARY KEY (ID));

