DROP TABLE PHONE;
DROP TABLE EMPLOYEE;
DROP TABLE EMP_PHONES;
CREATE TABLE PHONE (NUM VARCHAR(255) NOT NULL, TYPE VARCHAR(255), PRIMARY KEY (NUM));
CREATE TABLE EMPLOYEE (ID INTEGER NOT NULL, NAME VARCHAR(255), SALARY BIGINT, PRI_NUM VARCHAR(255), ZIP_CODE VARCHAR(255), STREET VARCHAR(255), STATE VARCHAR(255), CITY VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE EMP_PHONES (Employee_ID INTEGER NOT NULL, phones_NUM VARCHAR(255) NOT NULL, PRIMARY KEY (Employee_ID, phones_NUM));