DROP TABLE EMPLOYEE;

CREATE TABLE EMPLOYEE (ID INTEGER NOT NULL, NAME VARCHAR(255), DOB DATE, NOTUSED INTEGER, S_DATE DATE, PRIMARY KEY (ID));

INSERT INTO EMPLOYEE (ID, NAME, DOB, NOTUSED, S_DATE) VALUES (1, 'John', NULL, NULL, {d '2001-01-01'});
INSERT INTO EMPLOYEE (ID, NAME, DOB, NOTUSED, S_DATE) VALUES (2, 'Paul', NULL, NULL, {d '2002-04-08'});
INSERT INTO EMPLOYEE (ID, NAME, DOB, NOTUSED, S_DATE) VALUES (3, 'Sarah', NULL, NULL, {d '2003-06-10'});
INSERT INTO EMPLOYEE (ID, NAME, DOB, NOTUSED, S_DATE) VALUES (4, 'Patrick', NULL, NULL, {d '2004-07-01'});
INSERT INTO EMPLOYEE (ID, NAME, DOB, NOTUSED, S_DATE) VALUES (5, 'Joan', NULL, NULL, {d '2003-09-09'});
INSERT INTO EMPLOYEE (ID, NAME, DOB, NOTUSED, S_DATE) VALUES (6, 'Samantha', NULL, NULL, {d '2000-03-12'});
INSERT INTO EMPLOYEE (ID, NAME, DOB, NOTUSED, S_DATE) VALUES (7, 'Mark', NULL, NULL, {d '2004-11-01'});
INSERT INTO EMPLOYEE (ID, NAME, DOB, NOTUSED, S_DATE) VALUES (8, 'Ryan', NULL, NULL, {d '2005-12-05'});
INSERT INTO EMPLOYEE (ID, NAME, DOB, NOTUSED, S_DATE) VALUES (9, 'Jackie', NULL, NULL, {d '2006-01-03'});

