DROP TABLE EMPLOYEE;
DROP TABLE COMPANY;
CREATE TABLE EMPLOYEE (ID INTEGER NOT NULL, NAME VARCHAR(255), SALARY BIGINT, STREET VARCHAR(255), CITY VARCHAR(255), PROVINCE VARCHAR(255), POSTAL_CODE VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE COMPANY (ID INTEGER NOT NULL, STREET VARCHAR(255), CITY VARCHAR(255), STATE VARCHAR(255), ZIP_CODE VARCHAR(255), PRIMARY KEY (ID));
