DROP TABLE EMPLOYEE;
DROP SEQUENCE Emp_Seq;

CREATE TABLE EMPLOYEE (ID NUMBER NOT NULL, NAME VARCHAR(255), SALARY NUMBER, PRIMARY KEY (ID));

CREATE SEQUENCE Emp_Seq MINVALUE 1 START WITH 100 INCREMENT BY 50;

