DROP TABLE EMPLOYEE;
DROP TABLE ADDRESS;
DROP TABLE ID_GEN;

CREATE TABLE ADDRESS (ID INTEGER NOT NULL, CITY VARCHAR(255), STATE VARCHAR(255), STREET VARCHAR(255), ZIP VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE EMPLOYEE (ID INTEGER NOT NULL, NAME VARCHAR(255), SALARY BIGINT, ADDRESS_ID INTEGER,
                       CONSTRAINT ADDRESS_FK FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ID), PRIMARY KEY (ID));
CREATE TABLE ID_GEN (GEN_NAME VARCHAR(80), GEN_VAL INTEGER, PRIMARY KEY (GEN_NAME));

INSERT INTO ID_GEN (GEN_NAME, GEN_VAL) VALUES ('Emp_Gen', 0);
INSERT INTO ID_GEN (GEN_NAME, GEN_VAL) VALUES ('Addr_Gen', 10000);

