DROP TABLE EMPLOYEE;
CREATE TABLE EMPLOYEE (ID INTEGER NOT NULL, NAME VARCHAR(255), SALARY BIGINT, STREET VARCHAR(255), CITY VARCHAR(255), STATE VARCHAR(255), ZIP_CODE VARCHAR(255), PRIMARY KEY (ID));
