DROP TABLE EMPLOYEE;
DROP TABLE LOGRECORD;

CREATE TABLE LOGRECORD (ID INTEGER NOT NULL, EMPNO INTEGER, ACTION VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE EMPLOYEE (ID INTEGER NOT NULL, NAME VARCHAR(255), STARTDATE DATE, SALARY BIGINT);